# Generated by Django 2.2.1 on 2019-06-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Зображення буде відображатись на слайдері головної сторінки', null=True, upload_to='img', verbose_name='Зображення')),
                ('title', models.CharField(help_text='Тайл для бокса на слайдері', max_length=225, verbose_name='Title')),
                ('description', models.TextField(help_text='Текст для бокса в коробці', max_length=125, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Фотографія Слайдеру',
                'verbose_name_plural': 'Фотографії Сладеру',
            },
        ),
    ]
