# Generated by Django 2.2.1 on 2019-06-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Зображення')),
                ('title', models.CharField(help_text='Заголовок проекта', max_length=225, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Опис проекта', verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекти',
            },
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(help_text='Тайл для бокса на слайдері', max_length=225, verbose_name='Заголовок'),
        ),
    ]
