# Generated by Django 2.2.1 on 2019-06-19 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190619_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/blog', verbose_name='Зображення')),
                ('title', models.CharField(help_text='Заголовок статті', max_length=225, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Текст статті', verbose_name='Текст')),
                ('author', models.CharField(help_text='Автор', max_length=125, verbose_name='Автор')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата публікації статті')),
            ],
        ),
    ]
