# Generated by Django 2.2.2 on 2019-06-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Стаття Блогу', 'verbose_name_plural': 'Статті Блогу'},
        ),
    ]
