# Generated by Django 2.2.2 on 2019-06-27 13:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190620_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='a', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(help_text='Опис проекта', verbose_name='Опис'),
        ),
    ]
