# Generated by Django 2.2.1 on 2019-06-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190620_1246'),
        ('main', '0004_auto_20190620_1213'),
    ]

    operations = [
    ]
