# Generated by Django 2.2.2 on 2019-06-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190627_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='description',
            new_name='mce_description',
        ),
    ]
