# Generated by Django 2.2.1 on 2019-06-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20190620_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва', max_length=125, verbose_name='Назва')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/partners', verbose_name='Зображення')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Посилання')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнери',
            },
        ),
    ]
