# Generated by Django 2.2.2 on 2019-06-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190627_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='mce_description',
        ),
        migrations.AddField(
            model_name='slider',
            name='mceDescription',
            field=models.TextField(default='a', help_text='Текст для бокса в коробці', max_length=125, verbose_name='Опис'),
            preserve_default=False,
        ),
    ]
