# Generated by Django 2.2.2 on 2019-06-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190627_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='mce_description',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='mceDescription',
            new_name='description',
        ),
    ]
